site_name: Keen

repo_url: https://github.com/samuel-s-marques/keen-py
repo_name: keen-py

site_author: Samuel Marques
site_description: Keen, as in keen observation, is a reconnaissance and OSINT tool for ethical hacking and penetration testing.

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Usage: getting-started/usage.md
      - Workspace: getting-started/workspace.md
      - API Keys Management: getting-started/api_keys_management.md
      - Modules:
          - getting-started/modules/index.md
          - Analysis:
              - Hudson Rock: getting-started/modules/analysis/hudson_rock.md
              - Leak Check: getting-started/modules/analysis/leak_check.md
          - Discovery:
              - DNS Enum: getting-started/modules/discovery/dns_enum.md
              - Historical DNS: getting-started/modules/discovery/historical_dns.md
              - Subdomain Enum: getting-started/modules/discovery/subdomain_enum.md
              - WHOIS: getting-started/modules/discovery/whois.md
          - Enumeration:
              - Email Enrichment: getting-started/modules/enumeration/email_enrichment.md
              - Email Verification: getting-started/modules/enumeration/email_verification.md
              - Github Enumeration: getting-started/modules/enumeration/github_enum.md
              - Holehe: getting-started/modules/enumeration/holehe.md
              - Phone Verification: getting-started/modules/enumeration/phone_verification.md
              - Sherlock: getting-started/modules/enumeration/sherlock.md
              - SOCMINT: getting-started/modules/enumeration/socmint.md
          - Web:
              - WAF/CDN Detection: getting-started/modules/web/waf_detection.md
          - Helpers:
              - Email to Username: getting-started/modules/helpers/email_to_username.md
              - URL to Domain: getting-started/modules/helpers/url_to_domain.md
  - Developer:
      - API: developer/api.md
  - About:
      - Contributing: about/contributing.md
      - License: about/license.md
      - Roadmap: about/roadmap.md
      - Changelog: about/changelog.md
theme: readthedocs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
