site_name: Keen

repo_url: https://github.com/samuel-s-marques/keen-py
repo_name: keen-py

site_author: Samuel Marques
site_description: Keen, as in keen observation, is a reconnaissance and OSINT tool for ethical hacking and penetration testing.

nav:
        - Home: index.md
        - Getting Started:
                  - Installation: getting-started/installation.md
                  - Usage: getting-started/usage.md
                  - Preferences: getting-started/preferences.md
                  - Workspace Management: getting-started/workspace_management.md
                  - Timeline Management: getting-started/timeline_management.md
                  - API Keys Management: getting-started/api_keys_management.md
                  - Proxy Management: getting-started/proxy_management.md
                  - Magic Engine: getting-started/magic_engine.md
                  - Web Server: getting-started/web.md
                  - AI Partner: getting-started/ai_partner.md
        - Modules:
                  - Selecting and Using a Module: modules/index.md
                  - Analysis:
                            - Hudson Rock: modules/analysis/hudson_rock.md
                            - Leak Check: modules/analysis/leak_check.md
                  - Discovery:
                            - DNS Enum: modules/discovery/dns_enum.md
                            - Historical DNS: modules/discovery/historical_dns.md
                            - Subdomain Enum: modules/discovery/subdomain_enum.md
                            - WHOIS: modules/discovery/whois.md
                  - Enumeration:
                            - Domain Enrichment: modules/enumeration/domain_enrichment.md
                            - Email Enrichment: modules/enumeration/email_enrichment.md
                            - Email Verification: modules/enumeration/email_verification.md
                            - Email Finder: modules/enumeration/email_finder.md
                            - Github Enumeration: modules/enumeration/github_enum.md
                            - Phone Verification: modules/enumeration/phone_verification.md
                            - Sherlock: modules/enumeration/sherlock.md
                            - User Scanner: modules/enumeration/user_scanner.md
                  - Web:
                            - WAF/CDN Detection: modules/web/waf_detection.md
                  - Helpers:
                            - Email to Username: modules/helpers/email_to_username.md
                            - Org to Domain: modules/helpers/org_to_domain.md
                            - URL to Domain: modules/helpers/url_to_domain.md
        - Developer:
                  - Developing New Modules: developer/developing_new_modules.md
        - About:
                  - Contributing: about/contributing_to_keen.md
                  - License: about/license.md
                  - Roadmap: about/roadmap.md
                  - Changelog: about/changelog.md
theme: readthedocs
markdown_extensions:
        - admonition
        - pymdownx.details
        - pymdownx.superfences
        - pymdownx.arithmatex:
                  generic: true

exclude_docs: |
        requirements-docs.txt

extra_javascript:
        - https://unpkg.com/katex@0/dist/katex.min.js
        - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
        - _js/katex.js

extra_css:
        - https://unpkg.com/katex@0/dist/katex.min.css
